# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('relation_category', models.CharField(default=b'C', max_length=1, verbose_name=b'Account Type', choices=[(b'C', b'Client'), (b'V', b'Vendor')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirTicketDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=255, blank=True)),
                ('guest_name', models.TextField()),
                ('no_of_guests', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('airlines', models.CharField(max_length=255, blank=True)),
                ('sector', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255, blank=True)),
                ('destination_type', models.CharField(blank=True, max_length=1, choices=[(b'D', b'Domestic'), (b'I', b'International')])),
                ('start_date', models.DateField(null=True, blank=True)),
                ('return_date', models.DateField(null=True, blank=True)),
                ('basic_fare', models.DecimalField(max_digits=10, decimal_places=2)),
                ('pnr', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-booking_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reference', models.CharField(max_length=255, blank=True)),
                ('last_name', models.CharField(max_length=255, blank=True)),
                ('phone1', models.CharField(max_length=255, blank=True)),
                ('phone2', models.CharField(max_length=255, blank=True)),
                ('email1', models.CharField(max_length=255, blank=True)),
                ('email2', models.CharField(max_length=255, blank=True)),
                ('address1', models.CharField(max_length=255, blank=True)),
                ('address2', models.CharField(max_length=255, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, blank=True)),
                ('account_head', models.ForeignKey(to='ocndata.AccountHead')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_head'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('credit_note_type', models.CharField(default=b'T', max_length=1, choices=[(b'T', b'Air Ticket'), (b'H', b'Hotel'), (b'P', b'Package'), (b'V', b'Visa'), (b'I', b'Travel Insurance')])),
                ('old_docket_no', models.IntegerField()),
                ('new_purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('new_sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('new_profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('new_payment_mode', models.CharField(blank=True, max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=255, blank=True)),
                ('guest_name', models.TextField()),
                ('no_of_guests', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('hotel', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255, blank=True)),
                ('destination_type', models.CharField(blank=True, max_length=1, choices=[(b'D', b'Domestic'), (b'I', b'International')])),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('duration', models.IntegerField(null=True, blank=True)),
                ('meal_plan', models.CharField(default=b'CP', max_length=3, choices=[(b'EP', b'Room Only'), (b'CP', b'Room + Breakfast'), (b'MAP', b'Room + Breakfast + Dinner'), (b'AP', b'Room + All Meals'), (b'DU', b'Day Use'), (b'AU', b'All Inclusive'), (b'OTH', b'Others')])),
                ('hotel_confirmation_no', models.CharField(max_length=255, blank=True)),
                ('account_head', models.ForeignKey(to='ocndata.Client')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=255, blank=True)),
                ('guest_name', models.TextField()),
                ('no_of_guests', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('hotel', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255, blank=True)),
                ('destination_type', models.CharField(blank=True, max_length=1, choices=[(b'D', b'Domestic'), (b'I', b'International')])),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('duration', models.IntegerField(null=True, blank=True)),
                ('meal_plan', models.CharField(default=b'CP', max_length=3, choices=[(b'EP', b'Room Only'), (b'CP', b'Room + Breakfast'), (b'MAP', b'Room + Breakfast + Dinner'), (b'AP', b'Room + All Meals'), (b'DU', b'Day Use'), (b'AU', b'All Inclusive'), (b'OTH', b'Others')])),
                ('package_inclusions', models.CharField(max_length=255)),
                ('package_confirmation_no', models.CharField(max_length=255, blank=True)),
                ('account_head', models.ForeignKey(to='ocndata.Client')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelInsuranceDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=255, blank=True)),
                ('guest_name', models.TextField()),
                ('no_of_guests', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('insurance_provider', models.CharField(max_length=3, choices=[(b'BJ', b'Bajaj Allianz'), (b'AIG', b'Tata AIG'), (b'LOM', b'ICICI Lombard'), (b'OTH', b'Others')])),
                ('insurance_plan', models.CharField(max_length=30)),
                ('destination_country', models.CharField(max_length=255)),
                ('policy_no', models.CharField(max_length=255, blank=True)),
                ('account_head', models.ForeignKey(to='ocndata.Client')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reference', models.CharField(max_length=255, blank=True)),
                ('last_name', models.CharField(max_length=255, blank=True)),
                ('phone1', models.CharField(max_length=255, blank=True)),
                ('phone2', models.CharField(max_length=255, blank=True)),
                ('email1', models.CharField(max_length=255, blank=True)),
                ('email2', models.CharField(max_length=255, blank=True)),
                ('address1', models.CharField(max_length=255, blank=True)),
                ('address2', models.CharField(max_length=255, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255, blank=True)),
                ('company_name', models.CharField(max_length=255)),
                ('account_head', models.ForeignKey(to='ocndata.AccountHead')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_head'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=255, blank=True)),
                ('guest_name', models.TextField()),
                ('no_of_guests', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=15, choices=[(b'CREDIT', b'Credit'), (b'CCVBICICIVisa', b'Credit Card VB ICICI Visa (5002)'), (b'CCVBICICIAmex', b'Credit Card VB ICICI Amex (83004)'), (b'CCVBHDFC', b'Credit Card VB HDFC (9197)'), (b'CCVBINDUSIND', b'Credit Card VB IndusInd AMEX (10005)'), (b'CCVB/AKBAMEX', b'Credit Card VB/AKB AMEX (22019)'), (b'CCVBAMEXJET', b'Credit Card VB AMEX JET (51008)'), (b'CCGSHDFCJET', b'Credit Card GS HDFC JET (9643)'), (b'CCVBAMEXCHRG', b'Credit Card VB/AKB AMEX CHARGE (41018)'), (b'CCAKBAMEXJET', b'Credit Card AKB AMEX JET (31000)'), (b'CCAKBHDFCJET', b'Credit Card AKB HDFC JET (2076)'), (b'CCAKBICICIAMXJT', b'Credit Card AKB ICICI AMEX JET (35007)'), (b'CCAB/SBAMEX', b'Credit Card AB/SB AMEX (02018)'), (b'CCAB/SBAMEXJET', b'Credit Card AB/SB AMEX JET (61010)'), (b'CCABAMEX', b'Credit Card AB AMEX (21004)'), (b'CCABAMEXJET', b'Credit Card AB AMEX JET (91008)'), (b'CCABSBI', b'Credit Card AB SBI (9295)'), (b'CCABHDFC', b'Credit Card AB HDFC (3748)'), (b'CCABICICIAmex', b'Credit Card AB ICICI Amex (00008)'), (b'CCABSTANCHART', b'Credit Card AB StanChart (5244)'), (b'CCABINDUSIND', b'Credit Card AB/AKB IndusInd (8207)'), (b'CCSBSBI', b'Credit Card SB SBI (6497)'), (b'CCSBJETHDFC', b'Credit Card SB JET HDFC (7682)'), (b'NEFTOTHDFC', b'NEFT Oceana HDFC'), (b'NEFTOTICICI', b'NEFT Oceana ICICI'), (b'NEFTOTINDIAN', b'NEFT Oceana Indian Bank'), (b'CASH', b'Cash'), (b'REMITTANCE', b'Remittance'), (b'CHEQUE', b'Cheque'), (b'DD', b'Demand Draft'), (b'NBOTHDFC', b'Net Banking Oceana HDFC'), (b'NBOTICICI', b'Net Banking Oceana ICICI'), (b'NBOTINDIAN', b'Net Banking Oceana Indian Bank'), (b'OTH', b'Others'), (b'CCVBAMEXCHRG', b'Credit Card VB AMEX CHARGE CARD (41018)'), (b'CCSONAMHDFCJET', b'Credit Card AKB SONAM HDFC JET (8539)')])),
                ('purchase', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sale', models.DecimalField(max_digits=10, decimal_places=2)),
                ('profit', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('invoice_no', models.IntegerField(null=True, blank=True)),
                ('purchase_invoice_no', models.CharField(max_length=255, blank=True)),
                ('invoice_dispatch_date', models.DateField(null=True, blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('tally_narration', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_submit_to_accounts', models.BooleanField(default=False, verbose_name=b'Submit to Accounts')),
                ('is_purchase_received', models.BooleanField(default=False, verbose_name=b'Purchase Received')),
                ('is_invoice_created', models.BooleanField(default=False, verbose_name=b'Invoice Created')),
                ('is_tally_entered', models.BooleanField(default=False, verbose_name=b'Entered in Tally')),
                ('destination_country', models.CharField(max_length=255)),
                ('visa_type', models.CharField(default=b'T', max_length=2, choices=[(b'T', b'Tourist'), (b'TT', b'Tourist Tatkal'), (b'TR', b'Transit'), (b'B', b'Business'), (b'BT', b'Business Tatkal')])),
                ('account_head', models.ForeignKey(to='ocndata.Client')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(to='ocndata.Vendor')),
            ],
            options={
                'ordering': ['-booking_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='travelinsurancedocket',
            name='vendor',
            field=models.ForeignKey(to='ocndata.Vendor'),
        ),
        migrations.AddField(
            model_name='packagedocket',
            name='vendor',
            field=models.ForeignKey(to='ocndata.Vendor'),
        ),
        migrations.AddField(
            model_name='hoteldocket',
            name='vendor',
            field=models.ForeignKey(to='ocndata.Vendor'),
        ),
        migrations.AddField(
            model_name='airticketdocket',
            name='account_head',
            field=models.ForeignKey(to='ocndata.Client'),
        ),
        migrations.AddField(
            model_name='airticketdocket',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airticketdocket',
            name='vendor',
            field=models.ForeignKey(to='ocndata.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together=set([('account_head', 'company_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('account_head', 'first_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together=set([('name', 'relation_category')]),
        ),
    ]
